name: build

on: [push, create]

jobs:
  build_matrix:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04']
        ruby: ['2.6', '2.7', '3.0', '3.1']

    runs-on: ${{ matrix.os }}

    steps:
      # Environment setup
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rubocop
        run: |
          bundle exec rubocop --display-cop-names

      - name: Run tests
        run: |
          bundle exec rspec

  build:
    needs: [build_matrix]
    runs-on: ubuntu-20.04
    steps:
      - name: Dummy for branch status checks
        run: |
          echo "build complete"

  release:
    runs-on: ubuntu-20.04

    needs:
      - build

    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1

      - name: Create credentials
        run: |
          mkdir ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${{ secrets.RUBYGEMS_TOKEN }}
          EOF
          chmod 0600 /home/runner/.gem/credentials

      - name: Publish gem
        run: |
          gem build puma-plugin-telemetry.gemspec
          gem push puma-plugin-telemetry-*.gem
