name: build

on: [push, create]

jobs:
  build_matrix:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04']
        ruby: ['2.6', '2.7', '3.0']

    runs-on: ${{ matrix.os }}

    steps:
      # Environment setup
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-$(lsb_release -rs)-gems-${{ hashFiles('**/Gemfile.lock')}}-${{ matrix.ruby }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          gem install bundler

          bundle config path vendor/bundle

          bundle install

      - name: Run rubocop
        run: |
          bundle exec rubocop --display-cop-names

      - name: Run tests
        run: |
          bundle exec rspec

  build:
    needs: [build_matrix]
    runs-on: ubuntu-latest
    steps:
      - name: Dummy for branch status checks
        run: |
          echo "build complete"

  release-gemfury:
    needs: build
    if: contains(github.ref, 'tags') && github.event_name == 'create'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Prepare Gemfury
        run: |
          mkdir -p ~/.gem
          echo -e "---\n:fury_push_token: ${{ secrets.GEMFURY_TOKEN }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials

      - name: Build Gem
        run: |
          gem build *.gemfury.gemspec

      - name: Publish Gem
        run: |
          gem push *.gem --key fury_push_token \
                         --host https://push.fury.io/babbel

  release-github:
    needs: build
    if: contains(github.ref, 'tags') && github.event_name == 'create'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: babbel/publish-gem@v1
        with:
          gemspec-file: puma-plugin-telemetry.gemspec
