name: build

on: [push, create]

jobs:
  build_matrix:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04']
        ruby: ['2.6', '2.7', '3.0', '3.1']

    runs-on: ${{ matrix.os }}

    steps:
      # Environment setup
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-$(lsb_release -rs)-gems-${{ hashFiles('**/Gemfile.lock')}}-${{ matrix.ruby }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          gem install bundler

          bundle config path vendor/bundle

          bundle install

      - name: Run rubocop
        run: |
          bundle exec rubocop --display-cop-names

      - name: Run tests
        run: |
          bundle exec rspec

  build:
    needs: [build_matrix]
    runs-on: ubuntu-latest
    steps:
      - name: Dummy for branch status checks
        run: |
          echo "build complete"

  release:
    needs: build
    if: contains(github.ref, 'tags') && github.event_name == 'create'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - uses: babbel/publish-gem@v1
